# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Publish Scripts
version: "1.0.0"
slug: publish-scripts
description: A FastAPI-based add-on for publishing and managing scripts in Home Assistant with REST API interface
url: "https://github.com/zutlik/ha-addons/tree/main/publish-scripts"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  HOME_ASSISTANT_TOKEN: "your_home_assistant_token_here"
schema:
  HOME_ASSISTANT_TOKEN: "str"
image: "m3nadav/zutlik:latest"
