# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Publish Scripts
version: "1.2.0"
slug: publish-scripts
description: Home Assistant addon for managing scripts and ngrok tunnels
url: "https://github.com/home-assistant/addons-example/tree/main/publish-scripts"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  HOME_ASSISTANT_TOKEN: "your_token_here"
  HA_BASE_URL: "http://supervisor/core/api"
  NGROK_AUTH_TOKEN: ""
schema:
  HOME_ASSISTANT_TOKEN: "str"
  HA_BASE_URL: "str?"
  NGROK_AUTH_TOKEN: "str"
image: "ghcr.io/home-assistant/{arch}-addon-publish-scripts"
