# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Publish Scripts
version: "1.0.0"
slug: publish-scripts
description: A FastAPI-based add-on for publishing and managing scripts in Home Assistant with REST API interface
url: "https://github.com/zutlik/ha-addons/tree/main/publish-scripts"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  HOME_ASSISTANT_TOKEN: "your_token_here"
  HA_BASE_URL: "http://supervisor/core/api"
  NGROK_AUTH_TOKEN: ""
schema:
  HOME_ASSISTANT_TOKEN: "str"
  HA_BASE_URL: "str?"
  NGROK_AUTH_TOKEN: "str"
restart_policy: unless-stopped
image: "m3nadav/zutlik"
